{
 "title": "Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Triton - Success/Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(nv_inference_request_success_total{service_name=\"triton\"}[1m]))",
     "legendFormat": "Success {{label_name}}"
    },
    {
     "expr": "sum(increase(nv_inference_request_failure_total{service_name=\"triton\"}[1m]))",
     "legendFormat": "Failure {{label_name}}"
    }
   ]
  },
  {
   "title": "API - Endpoint Success/Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_milliseconds_count{service_name=\"glygateway\", status=\"200\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(http_server_requests_milliseconds_count{service_name=\"glygateway\", status=\"422\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triton - Inference Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(rate(nv_inference_request_duration_us_total{model=\"gemma-3-1b-it_tensorrt_llm_bls\"}[1m]) / 1000) / (rate(nv_inference_count_total{model=\"gemma-3-1b-it_tensorrt_llm_bls\"}[1m]))",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "API - Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_milliseconds_count{service_name=\"glygateway\"}[1m]))",
     "legendFormat": "Requests count {{label_name}}"
    }
   ]
  },
  {
   "title": "Triton - Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us_total{service_name=\"triton\"}[1m]) / (rate(nv_inference_count_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API - Apply Template/Stream Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "1000 * sum(increase(apply_template_milliseconds_sum{service_name=\"glygateway\"}[1m])) / sum(increase(apply_template_milliseconds_count{service_name=\"glygateway\"}[1m]))",
     "legendFormat": "Apply template {{label_name}}"
    },
    {
     "expr": "sum(increase(stream_tokens_milliseconds_sum{service_name=\"glygateway\"}[1m])) / (sum(increase(stream_tokens_milliseconds_count{service_name=\"glygateway\"}[1m])))",
     "legendFormat": "Stream tokens {{label_name}}"
    }
   ]
  }
 ]
}