# Image light enough we just redownload? upload to ecr later if needed
# global:
#   imageRegistry: 

# Persist Grafana's SQLite DB so UI-created dashboards/users survive pod restarts
persistence:
  enabled: true
  type: pvc
  size: 5Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: ebs-sc 

# # So that we can serve this in the same domain name as the gateway
# grafana.ini:
#   server:
#     root_url: "%(protocol)s://%(domain)s/grafana/"
#     serve_from_sub_path: true
