networks:
  observability:
    external: true

services:
  glygateway:
    image: glygateway:latest
    networks: [observability]
    ports:
      - "8090:8090"
    volumes:
      - ./target/app.jar:/app/app.jar
    entrypoint: ["java", "-jar", "/app/app.jar"]
    #environment:
      #JAVA_TOOL_OPTIONS: "-javaagent:agent.jar"
      #OTEL_SERVICE_NAME: "glygateway"
      #OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      #OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
      #OTEL_JAVAAGENT_DEBUG: true
      #OTEL_TRACES_EXPORTER: "otlp"
      #OTEL_METRICS_EXPORTER: "otlp"
      #OTEL_LOGS_EXPORTER: "otlp"
    restart: unless-stopped


