{{- if .Values.storage.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pv.name }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes: {{ toJson .Values.storage.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.storage.pv.reclaimPolicy }}
  hostPath:
    path: {{ .Values.storage.pv.hostPath | quote }}
  # Direct binding pvc to pv so storageClassName just set it to pv name
  storageClassName: {{ .Values.storage.pv.name }}
{{- end }}
