apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.size }}
  accessModes: {{ toJson .Values.pv.accessModes }}
  storageClassName: {{ .Values.pv.storageClassName | quote }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}
  hostPath:
    path: {{ .Values.pv.hostPath | quote }}

