apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
  namespace: {{ .Values.storage.namespace }}
spec:
  accessModes: {{ toJson .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.s3.enabled }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  {{- end }}
  {{- if .Values.storage.pv.enabled }}
  # Direct binding pvc to pv so storageClassName just set it to pv name
  storageClassName: {{ .Values.storage.pv.name | quote }}
  {{- end }}
