spring:
  application:
    name: glygateway
  main:
    banner-mode: "off"

server:
  port: 8090

triton:
  host: "triton.observability.svc.cluster.local"
  http-port: 8000
  grpc-port: 8001
  timeout-ms: 30000

models:
  gemma:
    max-tokens: 4096 
    temperature: 0.5
    top-p: 0.95
    top-k: 0
  gemma3:
    max-tokens: 4096 
    temperature: 0.5
    top-p: 0.95
    top-k: 0

# Auto loaded in by otlp auto config
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,metrics"
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-edge-opentelemetry-collector.observability.svc.cluster.local:4318/v1/traces
    metrics:
      export:
        url: http://otel-edge-opentelemetry-collector.observability.svc.cluster.local:4318/v1/metrics
        step: 5s
    opentelemetry:
      resource-attributes:
        service.name: ${spring.application.name}


logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

