model_repository: /home/gly/projects/netflix/inference-server/checkpoints/gemma-3-1b-it-engine-from-triton-cli/models
output_model_repository_path: /home/gly/projects/netflix/inference-server/model_analyzer_results/output
override_output_model_repository: true

model_type: LLM
client_protocol: grpc

triton_launch_mode: docker
triton_docker_image: nvcr.io/nvidia/tritonserver:25.06-trtllm-python-py3


genai_perf_flags:
  backend: tensorrtllm 
  streaming: true


profile_models:
  - gemma-3-1b-it


