networks:
  observability:
    external: true

services:
  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo/tempo-data:/var/tempo

  otel-collector:
    image: otel/opentelemetry-collector:0.101.0
    networks: [observability]
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otelcol/otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    restart: unless-stopped
    depends_on: [tempo, prometheus, grafana]

  tempo:
    image: *tempoImage 
    networks: [observability]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - ./tempo/tempo-data:/var/tempo
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    depends_on: [init]

  prometheus:
    image: prom/prometheus:latest
    networks: [observability]
    command: ["--config.file=/etc/prometheus/prometheus.yaml"]
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro

  grafana:
    image: grafana/grafana:latest
    networks: [observability]
    ports: 
      - "3000:3000"
    volumes:
      - ./grafana/grafana_custom.ini:/etc/grafana/grafana_custom.ini:ro
      - ./grafana/datasources/grafana_data_sources.yaml:/etc/grafana/provisioning/datasources/grafana_data_sources.yaml:ro
    environment:
      - "GF_PATHS_CONFIG=/etc/grafana/grafana_custom.ini"

