{{- if .Values.mountedCode.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mountedCode.pv.name }}
spec:
  capacity:
    storage: {{ .Values.mountedCode.pv.size }}
  accessModes: {{ toJson .Values.mountedCode.pv.accessModes }}
  storageClassName: {{ .Values.mountedCode.pv.storageClassName | quote }}
  persistentVolumeReclaimPolicy: {{ .Values.mountedCode.pv.reclaimPolicy }}
  hostPath:
    path: {{ .Values.mountedCode.pv.hostPath | quote }}
{{- end }}

