tempo:
  server:
    http_listen_port: 3200   # exposes /metrics; Prom scrape optional
  storage:
    trace:
      backend: local

metricsGenerator:
  enabled: true
  remoteWriteUrl: "http://prometheus-server.observability.svc.cluster.local:9090/api/v1/write"   


service:
  type: ClusterIP


# Receive traces via OTLP (so your apps or OTel Collector can send here)
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
  # Have not figured out how to disable unused ports for jaeger and opencensus
  jaeger: 
  opencensus: 

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app 
          operator: In
          values: ["central-node-label"]
