image:
  # Use ecr image for faster deployment
  imageName: "762853498770.dkr.ecr.us-east-1.amazonaws.com/glygateway"

# Allowed to be scheduled on GPU nodes 
# to keep cost down i dont want more nodes just for api lol.
# This might affect triton performance
tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
