mode: deployment
image:
  # Using contrib version for prometheus support
  repository: otel/opentelemetry-collector-contrib
  tag: 0.90.0 # Use a specific, known-good tag
  pullPolicy: IfNotPresent

dnsConfig:
  options:
    - name: ndots
      value: "1"

service:
  type: ClusterIP

ports:
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP
  prometheus:
    enabled: true
    containerPort: 9464
    servicePort: 9464
    protocol: TCP
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false

# Core collector config
config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    batch: {}

  exporters:
    prometheus:
      # Expose a port on this container for prometheus to scrape
      endpoint: "0.0.0.0:9464"
      enable_open_metrics: true
      # Static label for all metrics exporting through this
      # Becareful not to have duplicate constant and variable labels
      # const_labels:
      #   pipeline: "edge-aggregated"
      resource_to_telemetry_conversion:
        enabled: true   # 👈 promote resource attrs to labels

    otlp/tempo:
      endpoint: "tempo.observability.svc.cluster.local:4317"
      tls:
        insecure: true

    logging:
      verbosity: detailed 

  # Pipelines—enable what you need
  service:
    telemetry:
      metrics:
        address: 0.0.0.0:8888
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/tempo]

      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus]

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app 
          operator: In
          values: ["central-node-label"]
