server:
  service:
    enabled: true
    servicePort: 9090
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  extraArgs:
    log.level: debug
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  # Allow to run as 65534 for init container
  securityContext:
    runAsNonRoot: false

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app 
            operator: In
            values: ["central-node-label"]

# centralized alerting component for prometheus ecosystem (Go to email/slack/...)
alertmanager:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app 
            operator: In
            values: ["central-node-label"]

# Add-on service that listens to Kubernetes api server
kube-state-metrics:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app 
            operator: In
            values: ["central-node-label"]

# Collect node metrics (hardware) so should run on all nodes
prometheus-node-exporter:

# Short lived tasks metrics that die too fast for prometheus to scrape them?
prometheus-pushgateway:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app 
            operator: In
            values: ["central-node-label"]

# Full Prometheus config (simple & explicit)
serverFiles:
  prometheus.yml:

    scrape_configs:
      # ====== EDIT THESE TARGETS ======
      - job_name: "otel-central-metrics"
        static_configs:
          - targets:
              - "otel-central-opentelemetry-collector.observability.svc.cluster.local:8888"
      - job_name: "otel-central"
        honor_labels: true
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - "otel-central-opentelemetry-collector.observability.svc.cluster.local:9464"
